#!/bin/bash
# ------------------------------------------------------------------------------
# clone_script.sh  -  installer for the R version of gAIRR-wgs
#
# What this does:
#   1. Locates the ORIGINAL gAIRR-wgs repository (expected one level up by
#      default, or in $GAIRR_ORIG).  The R entry points call into the
#      original's gAIRR_suite/scripts/ (50+ Python helpers) and
#      gAIRR_suite/material/ (FASTA + BWA index), so those must exist
#      somewhere locally.  We do NOT duplicate them: we symlink.
#   2. Installs two executable shims onto $PATH that dispatch to `Rscript`:
#          gAIRR_wgs   -> Rscript .../gAIRR_suite_R/gAIRR_wgs.R "$@"
#          gAIRR_extract -> Rscript .../gAIRR_suite_R/gAIRR_extract.R "$@"
#      Shims are installed into the active conda environment's bin/ if one
#      is active; otherwise into ~/.local/bin (make sure that's on $PATH).
#
# Usage:
#   # Option A: original repo is alongside this one (named "gAIRR-wgs-main")
#   bash clone_script.sh
#
#   # Option B: point explicitly
#   GAIRR_ORIG=/path/to/gAIRR-wgs-main bash clone_script.sh
# ------------------------------------------------------------------------------

set -euo pipefail

R_REPO_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# ---- 1. locate the original gAIRR-wgs -----------------------------------------
if [[ -z "${GAIRR_ORIG:-}" ]]; then
    for candidate in \
        "$R_REPO_DIR/../gAIRR-wgs-main" \
        "$R_REPO_DIR/../gAIRR-wgs" \
        "$R_REPO_DIR/../../gAIRR-wgs-main"; do
        if [[ -d "$candidate/gAIRR_suite/scripts" ]] && [[ -d "$candidate/gAIRR_suite/material" ]]; then
            GAIRR_ORIG="$(cd "$candidate" && pwd)"
            break
        fi
    done
fi

if [[ -z "${GAIRR_ORIG:-}" ]] || \
   [[ ! -d "$GAIRR_ORIG/gAIRR_suite/scripts" ]] || \
   [[ ! -d "$GAIRR_ORIG/gAIRR_suite/material" ]]; then
    cat >&2 <<EOF
Error: could not locate the ORIGINAL gAIRR-wgs repository.

The R version delegates all heavy-lifting to the original gAIRR_suite/scripts/
(Python helpers) and gAIRR_suite/material/ (FASTA references + BWA indices),
so the original must be available locally.

Fix one of the following, then re-run this script:
  - Clone https://github.com/AnthonyDNA/gAIRR-wgs as a sibling directory
    (the clone's folder should contain gAIRR_suite/scripts and gAIRR_suite/material).
  - OR set GAIRR_ORIG to its root, e.g.
        GAIRR_ORIG=/path/to/gAIRR-wgs bash clone_script.sh
EOF
    exit 1
fi

echo "Original gAIRR-wgs detected at: $GAIRR_ORIG"

# ---- 2. wire scripts/ and material/ into the R tree via symlink ----------------
ln -sfn "$GAIRR_ORIG/gAIRR_suite/scripts"  "$R_REPO_DIR/gAIRR_suite_R/scripts"
ln -sfn "$GAIRR_ORIG/gAIRR_suite/material" "$R_REPO_DIR/gAIRR_suite_R/material"
echo "Linked scripts/ and material/ into $R_REPO_DIR/gAIRR_suite_R/"

# ---- 3. sanity-check R and required tools -------------------------------------
if ! command -v Rscript >/dev/null 2>&1; then
    echo "Warning: Rscript not found on PATH. Install R before running the pipeline." >&2
fi
for tool in bwa samtools; do
    if ! command -v "$tool" >/dev/null 2>&1; then
        echo "Warning: $tool not found on PATH. gAIRR-wgs won't run without it." >&2
    fi
done

# ---- 4. install PATH shims ----------------------------------------------------
# Prefer the active conda environment's bin; otherwise fall back to ~/.local/bin.
if command -v python >/dev/null 2>&1; then
    ENV_BIN="$(python -c 'import sys, os; print(os.path.dirname(sys.executable))' 2>/dev/null || true)"
fi
if [[ -z "${ENV_BIN:-}" ]] || [[ ! -w "$ENV_BIN" ]]; then
    ENV_BIN="$HOME/.local/bin"
    mkdir -p "$ENV_BIN"
    echo "No writable conda env bin detected - installing shims to $ENV_BIN"
    echo "Make sure $ENV_BIN is on your \$PATH."
fi

cat > "$ENV_BIN/gAIRR_wgs" <<EOF
#!/bin/bash
# Shim generated by gAIRR-wgs R-version clone_script.sh
exec Rscript "$R_REPO_DIR/gAIRR_suite_R/gAIRR_wgs.R" "\$@"
EOF
chmod +x "$ENV_BIN/gAIRR_wgs"

cat > "$ENV_BIN/gAIRR_extract" <<EOF
#!/bin/bash
# Shim generated by gAIRR-wgs R-version clone_script.sh
exec Rscript "$R_REPO_DIR/gAIRR_suite_R/gAIRR_extract.R" "\$@"
EOF
chmod +x "$ENV_BIN/gAIRR_extract"

echo "Installed:"
echo "  $ENV_BIN/gAIRR_wgs"
echo "  $ENV_BIN/gAIRR_extract"
echo "Done."
